# Generated by Django 3.1 on 2020-08-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visualize',
            field=models.CharField(choices=[('1', 'Invisivel'), ('2', 'Visivel')], default='1', max_length=1),
        ),
    ]
